version: '3.8'

networks:
  mcl-network:
    driver: bridge

volumes:
  mcl-data:
    driver: local
  mcl-data-test:
    driver: local

services:
  nginx:
    image: nginx:1.25.3
    container_name: mcl-nginx
    ports:
      - "8081:80"
      - "443:443"
      # Port for xdebug (ensure this matches the remote_port in the xdebug.ini)
      # ?
      - "9002:9001"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - mcl-network

  mysql:
    image: mysql:8.0
    container_name: mcl-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mcl-data:/var/lib/mysql
      - ./docker/mysql/config/my.cnf:/etc/mysql/my.cnf
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    networks:
      - mcl-network

  mysql_test:
    image: mysql:8.0
    container_name: mcl-mysql-testing
    restart: unless-stopped
    env_file:
      - .env.testing
    environment:
      - MYSQL_ROOT_PASSWORD=test_pass_1
      - MYSQL_DATABASE=movies_content_list_test
      - MYSQL_USER=movies_content_list_test
      - MYSQL_PASSWORD=test_pass
    ports:
      - 8302:3306
    volumes:
      - mcl-data-test:/var/lib/mysql
      - ./docker/mysql/config/my.cnf:/etc/mysql/my.cnf
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    networks:
      - mcl-network

  php:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        XDEBUG_ENABLED: true
    container_name: mcl-php
    volumes:
      - ./:/var/www/html
      # Enable xdebug
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9001:9000"
    networks:
      - mcl-network
